Archive Python prototype scheduler
Also remove it from the CI.

diff --git a/archive/v2/robotmk/setup b/archive/v2/robotmk/setup
--- a/archive/v2/robotmk/setup
+++ b/archive/v2/robotmk/setup
@@ -4,12 +4,25 @@ set -e
 
 main() {
     setup_rust
+
+    setup_python_environment "${PYTHON_VERSION}"
+
     setup_powershell
+
     git config core.hooksPath .githooks
 }
 
-setup_rust() {
-    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - -y
+setup_python_environment() {
+    check_poetry_executable
+    export POETRY_VIRTUALENVS_IN_PROJECT=true
+    poetry install --with dev
+}
+
+check_poetry_executable() {
+    command -v poetry > /dev/null || {
+        echo "poetry executable not found, aborting. Installing poetry is non-trivial, please do it manually."
+        exit 1
+    }
 }
 
 setup_powershell() {
@@ -20,6 +33,10 @@ setup_powershell() {
     sudo apt-get update
     sudo apt-get install powershell
     pwsh -Command "Install-Module -Name PSScriptAnalyzer"
+}
+
+setup_rust() {
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - -y
 }
 
 main
